version: "3"
services:
  mysqld:
    image: mysql:5.7
    build: ./sql
    container_name: mysql57
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=root
      - TZ=Asia/Tokyo
    volumes:
      - ./sql/my.conf:/etc/mysql/conf.d
      - ./sql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306