spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hinberate:
      ddl-auto: update
