spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password:
  jpa:
    database: MYSQL
    hinberate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace


